### ISSUE TITLE
treat byte order mark (bom) as whitespace

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#10]
I have literally no idea how to do this if the string has already been converted into utf8? Does the parser need to be changed to be byte-oriented? How does this even work.

**Comment by Lucretiel** [comment]
Assuming you require UTF-8, it should be trivial to accept `char('\x{FEFF}')`, corresponding to `U+FEFF`. To the best of my knowledge, the BOM is only relevant in encodings that act on units larger than a byte (like UCS-2), which needs to know, for each pair of bytes in the input, which byte is high significance and which on is low (and which will therefore encode `U+FEFF` as `0xFE 0xFF` or `0xFF 0xFE` on the byte stream). For a UTF-8 stream, the unit-of-encoding is the byte, so there's no issues here; `U+FEFF` is always encoded on the stream as `0xEF 0xBB 0xBF`

**Comment by zkat** [comment]
Gonna deal with this a bit differently, so I'm gonna close this.
