### ISSUE TITLE
Extending primitives

### ISSUE THREAD

**Issue by tabatkins** [kdl-org/kdl#106]
#89 requests a new primitive type, the "symbol", which is similar to but distinguishable from strings so they can unambiguously distinguish between "constant values" (strings) and "variables" (symbols) in a value list.

There have been requests for other additional primitives as well, such as dates, or binary blobs. Right now either of these have to be encoded as strings, and require domain-specific knowledge to tell apart from "ordinary" strings; this also means you can't use the primitive's type to distinguish things and must instead rely on named values or a required position.

The only other way around these issues is to move this data down into the child list, encoding it as nodes: `symbol "foo"`, `date "1970-01-01"`, `base64 "..."`, etc. But then you run into the issue mentioned in #105, where you can no longer identify these nodes with names like named values, nor can you mingle them with other primitives; they're segregated into the child list on their own.

I agree with your stance so far on keeping the set of primitives small and simple, but believe a simple extension mechanism would allow most of these scenarios to be addressed with minimal pain.

----

Proposal: Add "tagged strings" as a new primitive type, written as `tag@"string"`. The @ separates the tag from the string syntax (so it's unambiguous with the `r` string prefix), and all string syntaxes are allowed.

No meaning is given to these; the tag is just an opaque identifier carried with the string, letting the user identify the data as having some specific additional meaning. Microsyntaxes within the string are still the user's responsibility; there's no further exposed structure (in particular, no nesting).

(I *think* the @ doesn't interfere with ident syntax, which allows `@` anywhere in it; you could have a tag named "foo@" by writing `foo@@"string"`.)

So dates could then be easily distinguished as `date@"1970-01-01"`, base-64-encoded data as `bin@"..."`, etc. I think the empty tag should be allowed as well, like `@"foo"`, to allow for easy encoding of trivial cases like the symbol/string distinction from #89.

**Comment by zkat** [comment]
I feel as though something like this might be better served by declaring desired interpretations in a Schema? (see #104) What's the actual value of inlining this kind of metadata? Is it a dynamic languages thing? Stuff like serde has no issue being told what a particular value is supposed to be, and I guess that's because the type defs are a schema of sorts...

**Comment by zkat** [comment]
It's late and I can't stop thinking about this and I'm now leaning towards type hints being a good and useful thing to have inline? I guess I'll sleep on it. I like keeping things simple but this would be a small addition, and I don't think there's any harm in having type *hints* if we're already expecting strings to be interpreted in different ways based on schema/context?

**Comment by tabatkins** [comment]
Yeah, getting *fancy* with stuff should be left to schemas, but allowing a *minor* bit of extensibility/categorization makes sense to me because KDL already allows you do that *if your data semantics happen to split along a number/string dichotomy*. If they don't (you have two types that need distinguishing that are both character-based), you're SOL currently, and have to rely solely on positional ordering, invent your own in-string tagging scheme, or fall back to using child nodes.

So long as we don't have tagging, we'll forever have requests for "one more primitive", I think.

**Comment by zkat** [comment]
ok so I like this idea after thinking more about it. How about:

```kdl
mynode val=20<u8>
```

or

```kdl
mynode val=(u8)20
```

?

**Comment by zkat** [comment]
(oh actually, the () syntax is really nice)

**Comment by zkat** [comment]
PR up over at #123, using the `(u8)123` syntax. Let's move discussion of specifics over there?

**Comment by larsgw** [comment]
> I don't think there's any harm in having type hints if we're already expecting strings to be interpreted in different ways based on schema/context?

I see I am a bit too late to give my opinion, but I think there is at least some small amount of harm in having there be multiple ways that the same thing can be achieved without knowing when to use which one. I guess that might be solved by good docs though.

**Comment by zkat** [comment]
Not too late! I'm happy to relitigate this as long as it's before 1.0 :)

Can you expand on what you're saying?

**Comment by larsgw** [comment]
I don't know, I think I changed opinions ~~twice~~ thrice in the meantime. This stuff is hard :) I think my point is that parsing with schemas and parsing with type hints may conflict, and that there should be docs that explain what happens in such cases. Since I can't decide whether I like type tags or not, whatever's fine with me. I don't think it's very hard to implement anyway.

**Comment by zkat** [comment]
We can clarify this but I think the answer is obvious: type annotations are _hints_/suggestions, whereas schemas are considered authoritative?

**Comment by larsgw** [comment]
I mean yes, that is pretty obvious. I don't know what I was thinking at this point honestly.

**Comment by zkat** [comment]
I don't think it was a silly question, and it might be worth clarifying, intention-wise. I've been trying to use the softest language I can for type annotations.

**Comment by tabatkins** [comment]
Ultimately, any schema conflict concern already has to address the difference between `node 1` and `node "1"`; adding in `node (u8)1` doesn't seem to add any new problem, just *perhaps* makes it easier to generate a conflict because there's more than four types.
