### ISSUE TITLE
allow unquoted non-ascii symbols

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#11]
Shouldn't need to quote 😀 as an identifier. Just freakin' allow it.

**Comment by tabatkins** [comment]
A relevant question then is - do you allow *all* non-ASCII (codepoints U+0080 and above) to be part of an ident, or do you limit some characters to avoid confusion?  In particular, do you want to exclude the unicode whitespace characters?

**Comment by zkat** [comment]
whitespace isn't allowed as part of identifies already. That should be made more clear in the spec, I guess 🤔

**Comment by zkat** [comment]
This is done.
