### ISSUE TITLE
KDL spec meta: `min` and `max` as properties?

### ISSUE THREAD

**Issue by Lucretiel** [kdl-org/kdl#110]
It struck me as a bit odd that `min` and `max` on a node or value descriptor appear as child nodes for that descriptor, rather than properties; any particular reason for this?

**Comment by zkat** [comment]
I decided it was more consistent for all "validators" to be actual children, for consistency. I was using `min` and `max` as properties at first, and as I started adding more validators, I realized it would be smoother/more consistent/future-proof to always make them children. Only specific, constrained metadata uses properties now.
