### ISSUE TITLE
Minor nitpick: commented-block grammar

### ISSUE THREAD

**Issue by larsgw** [kdl-org/kdl#128]
Current grammar for `commented-block`:

```
commented-block := ('*' [^\/] | [^*])*
```

As a regex, this would match `**/` even though it should not. In a regex the solution would be a lookahead I think (also for the case `*`, but I am not sure how best to represent that in this grammar syntax. `('*'+ [^*\/] | [^*])*` *would* work for the first case but not for `**` and `*` (or any trailing `*` for that matter).

**Comment by zkat** [comment]
ughghhghhhhhh nice catch. This is a frustrating one. We'll probably have to rewrite multi-line-comment to fix this. Do you want to give this a shot, or should I?

**Comment by larsgw** [comment]
I think `multi-line-comment` is wrong too, the nested `multiline-comment` should be able to go in between text from `commented-block`:

```
multi-line-comment := '/*' (commented-block | multi-line-comment) '*/'
```

If lookaheads are allowed it would become something like this:

```
multi-line-comment := '/*' (commented-block | multi-line-comment)* '*/'
commented-block := ('*' (?=[^\/]) | [^*])+
```

**Comment by zkat** [comment]
I'm trying to remember if any other terms actually require lookahead

**Comment by larsgw** [comment]
For kdljs I think I am using something like this

```
multi-line-comment := '/*' (multi-line-comment | commented-block)*? '*/'
commented-block := '*' | '/' | [^*/]+
```

With the question mark in `multi-line-comment` being a lazy modifier, and the order changed to prefer `multi-line-comment` over `commented-block` in each "iteration".

**Comment by larsgw** [comment]
I limited myself to regex too much. Does this work?

```
multi-line-comment := '/*' commented-block
commented-block := '*/' | (multi-line-comment | '*' | '/' | [^*/]+) commented-block
```

**Comment by larsgw** [comment]
The PEG.js equivalent seems to work so I'll make a PR

```
multi_line_comment = '/*' commented_block
commented_block = '*/' / (multi_line_comment / '*' / '/' / [^*/]+) commented_block
```
