### ISSUE TITLE
Magic Characters

### ISSUE THREAD

**Issue by swift2plunder** [kdl-org/kdl#140]
Sometimes serialization formats share the wire. When this happens, it's useful to be able to tell from reading the first couple characters that the content should be routed to parser X. For example, "<" is a sign that we're in the XML family, "(" that we're looking at s-exp, "{" would be JSON, "%" YAML, etc. I would like to suggest that starting KDL documents with a node comment, "/-" (perhaps with some convention regarding metadata, such as version) would be a good best practice and perhaps a reasonable protocol recommendation

**Comment by zkat** [comment]
I mean... your examples don't even work for the languages specified?

* `{` could be Dhall (comments) or JSON5, among others, for example.
* YAML doesn't need to start with `%`.
* JSON doesn't need to start with `{`. There's no requirement that the toplevel be an _object_. It could be an array! Or any other type.
* `<` could be html5

As such, I'm not sure there's much we can do here on the KDL side to facilitate this use case. Perhaps the approach needs to be addressed instead?
