### ISSUE TITLE
Default name of root node for flat sets of key-value pairs

### ISSUE THREAD

**Issue by nichtich** [kdl-org/kdl#146]
Ho do you express simple flat sets of key-value pairs in KDL? Such as a simple configuration file without nesting or a row from an SQL table. A example in INI File syntax:

~~~ini
answer=42
author="Douglas Adams"
work="The Hitchhiker's Guide to the Galaxy"
~~~

What workaround/encoding is recommended in KDL? Best use the empty string as root node name?

~~~kdl
"" answer=42 author="Douglas Adams" work="The Hitchhiker's Guide to the Galaxy"
~~~

A root node name for flat sets of key-value pairs could be recommended in **KViK** next to XiK and JiK.

----

Additional note, but [another issue](https://github.com/kdl-org/kdl/issues/147): bare node identifiers must not contain `=`, so the root node name could be the empty string (or another recommended value) by default. This is invalid in KDL 1.0.0, but could be read unambiguously by a forgiving parser:

~~~kdl
answer=42 author="Douglas Adams" work="The Hitchhiker's Guide to the Galaxy"
~~~

**Comment by larsgw** [comment]
I *think* the idiomatic encoding would be something like this:

```kdl
answer 42
author "Douglas Adams"
work "The Hitchhiker's Guide to the Galaxy"
```

**Comment by nichtich** [comment]
Thanks! The data model of KDL slightly differs from most other structuring languages (JSON, XML, INI, CSV...), so I was blinded. I'll move this to discussion.
