### ISSUE TITLE
An elixir implementation

### ISSUE THREAD

**Issue by IceDragon200** [kdl-org/kdl#155]
I have an elixir implementation https://github.com/IceDragon200/kuddle, it's not quite finished, It's still failing a few of the kdl tests which seem mostly floating-point related (i.e. 1.23E-1000 evaluates to 0, so I assume it's way over the limit and I'll need decimal for that) and slashdash issues here and there, as well as some illegal parser behaviour (i.e. allowing ids as values).

It should mostly work for the common cases

**Comment by zkat** [comment]
Omg my hero. I've been wanting to write an Elixir impl myself because I'm hacking on a Phoenix project. Thank you!

**Comment by zkat** [comment]
Could you please make a PR both to this repo and to the website to add this to the list of implementations?

**Comment by IceDragon200** [comment]
Just an update, all tests pass now, and I've published it to hex https://hex.pm/packages/kuddle
