### ISSUE TITLE
consider banning empty-string property names

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#17]
This would allow KDL parsers to reserve `""` as a special "key" that can be used to access children, making translation between JSON and KDL way way easier?

**Comment by larsgw** [comment]
If it's mostly for translating to JSON I would almost suggest reserving something like `"children"`, that makes it less of a hack and easier to work with in JavaScript (and similar programs, probably), i.e. `node.children` vs `node['']`.

**Comment by zkat** [comment]
I feel hesitant about reserving any specific keyword for use with this, though. Especially one that could be as common as `chilren`, don't you think?

The only other answer I've come up with so far is to stop allowing arbitrary string node names altogether, which would let us _actually_ reserve something without communicating any indention of it being usable as an arbitrary string key.

idk idk

**Comment by zkat** [comment]
I talked myself out of this whole idea.

The expected JS interface for KDL property access should be `node.get("prop")`, not `node["prop"]`. That solves the whole problem. Just treat them like maps and we're done!
