### ISSUE TITLE
allow child-{ to start on the following line?

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#18]
this would require parsers have a lot more lookahead so idk if I like it, but maybe it's fine. I probably have these infinite lookahead cases all over the place anyway.

**Comment by lilyball** [comment]
I don’t think this is necessary. If you want the `{` to be on a new line you can use an escline. It seems weird to say “in this one particular case, a newline is not considered semantically meaningful”.

**Comment by zkat** [comment]
That's fair! Let's go with that :)
