### ISSUE TITLE
KDL Identifiers can't have whitespace, not explicit in spec

### ISSUE THREAD

**Issue by Lucretiel** [kdl-org/kdl#188]
Per the spec:

> A bare Identifier is composed of any Unicode codepoint other than non-initial characters, followed by any number of Unicode codepoints other than non-identifier characters, so long as this doesn't produce something confusable for a Number, Boolean, or Null.
> 
> Identifiers are terminated by Whitespace or Newlines.
>
> Non-initial characters
> 
> The following characters cannot be the first character in a bare Identifier:
> 
>     Any decimal digit (0-9)
>     Any non-identifier characters
> 
> Non-identifier characters
> 
> The following characters cannot be used anywhere in a bare Identifier:
> 
>     Any codepoint with hexadecimal value 0x20 or below.
>     Any codepoint with hexadecimal value higher than 0x10FFFF.
>     Any of \/(){}<>;[]=,"

Unless it's considered implicit by the terminator clause, it doesn't appear in the spec that identifiers also can't contain whitespace.

**Comment by hkolbeck** [comment]
The grammar seems pretty unambiguous, unless I'm missing something? `identifier-char := unicode - linespace - [\/(){}<>;[]=,"]`

IMO it's fine to leave implicit in the longform explanation

**Comment by Lucretiel** [comment]
Oh good catch, ty
