### ISSUE TITLE
Terminology requests

### ISSUE THREAD

**Issue by Lucretiel** [kdl-org/kdl#190]
For the assistance of implementers, I'd like to propose we add a set of terminology to help group related concepts in KDL. Specifically, I'm interested in a unifying term for:

- The properties and arguments associated with a node.
- The properties, arguments, and the set of children associated with a node.

In [`kaydle`](github.com/Lucretiel/kaydle) I've been using "Entity" interchangeably for both of these, but I don't love that. I was thinking something like a "Component" (for all things belonging to a node) and "Primitive Component" (for everything except the set of children). Of course, I'm happy to hear bikeshedding for this. Under this model, a single component would be any individual value, an individual property (the key-value pair collectively), or the set of children as a whole.

This terminology shouldn't really be needed by actual KDL users, but it'll be convenient for implementors to be able to have a common term to refer to all of the things belonging to a single node, because often these are iterated / grouped collectively in the course of parsing.

**Comment by zkat** [comment]
`entity` sounds fine by me. Everything else I can think of has a lot of overlap with other languages that would prove confusing?

**Comment by hkolbeck** [comment]
I also can't think of anything better than `entity`.

**Comment by tabatkins** [comment]
I'm using entity now for the props/values object, and yeah, it works fine for me.
