### ISSUE TITLE
Differentiation between "no children" and "empty children"

### ISSUE THREAD

**Issue by djmattyg007** [kdl-org/kdl#218]
I'm wondering if implementations should be explicit about the difference between the following two documents:

```
node
```

```
node {
}
```

At the moment, I'm interpreting them identically. When it comes time to serialise the document, both inputs would be encoded as the first example. Is this correct?

**Comment by zkat** [comment]
This is fine as long as your parser is a data-oriented parser. Document-oriented parsers should probably preserve the empty child block, but they're already preserving a lot of extraneous things like whitespace so it's not a big deal to do it either way.

**Comment by tabatkins** [comment]
Strong agree on both. The distinction doesn't matter for data parsers, and it *already* matters for document parsers that want to preserve the original structure as much as possible. So it shouldn't be part of the KDL data model itself.

**Comment by hkolbeck** [comment]
kdl4j exposes the difference in the model objects it uses to represent nodes, but I don't think that needs to be a general requirement. On the output side, printing empty children is a config setting.

**Comment by hkolbeck** [comment]
My inclination is to make the tests translate empty child -> no child, and add a note to the test README.

**Comment by zkat** [comment]
I feel like we should make a call either way. There should definitely be a decision.

I'm also inclined towards empty child -> no child, mostly because that means that you don't allocate unnecessarily ;p

**Comment by tabatkins** [comment]
cool, PR incoming shortly
