### ISSUE TITLE
Vim syntax highlighting

### ISSUE THREAD

**Issue by auctumnus** [kdl-org/kdl#258]
I use Vim as my editor, and it'd be really nice if there were a Vim syntax file or tree-sitter highlighter.

There's prior work at [this repo](https://github.com/Unoqwy/tree-sitter-kdl), but it doesn't appear to actually work (installed the parser and such and it didn't highlight anything, but I'm also not 100% on if I installed it right 😅)

I started an attempt at a regular Vim syntax, but I'm not sure if slashdash comments can be represented; with rules like
```vim
syn region kdlSlashdashComment     start="^\@<!/-" end="\s"
syn region kdlSlashdashNodeComment start="/-{"     end="}"  contains=kdlBlock
syn region kdlSlashdashNodeComment start="^\@<=/-" end="}"
```
which are just translated from the vscode syntax patterns (as far as i know!), I end up with highlights like
![image](https://user-images.githubusercontent.com/37276280/153044904-a2e78cc6-342c-4536-8d2e-8842ccfa54dc.png)
(with all of the code - presumably up to a closing } - commented).

**Comment by a-kenji** [comment]
> Tree-sitter is a neovim specific thing I believe

Neovim integrated tree-sitter bindings natively, but I don't think that means vim couldn't make use of tree-sitter through a plugin.

**Comment by spaarmann** [comment]
I started working on a [tree-sitter parser](https://github.com/spaarmann/tree-sitter-kdl). It's not complete yet (notably type annotations and `/-` comments are missing right now) but it's getting there :)

I also included some installation instructions for use with nvim-treesitter in the README; I think the step of having to manually copy in the `highlights.scm` file is easily missed.

**Comment by eyelidlessness** [comment]
@spaarmann are you interested in contributions to the tree-sitter grammar? Some/all of the caveats currently listed in your README are areas I could potentially help, and would be a great jumping off point for use cases like generating type definitions for consuming languages.

**Comment by spaarmann** [comment]
Yes, definitely! I meant to get at least slash-dash comments working but I've been super busy lately so I haven't even started on it yet; any contributions are much appreciated.

**Comment by imsnif** [comment]
I also made this: https://github.com/imsnif/kdl.vim
It's not fully-featured, but I think it's a pretty good experience all-in-all.

**Comment by sp3ctum** [comment]
Hi all, I found out the neovim plugin [nvim-treesitter supports](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#supported-languages) kdl out of the box:

> [kdl](https://github.com/amaanq/tree-sitter-kdl) (maintained by @amaanq)

It looks like it was added about a year ago, see the project's kdl related PRs [here](https://github.com/nvim-treesitter/nvim-treesitter/pulls?q=is%3Apr+kdl+is%3Aclosed)

In neovim v0.9.5 I was able to enable using the lazyvim setup using the following plugin spec:

```lua
-- ~/.config/nvim/lua/plugins/treesitter.lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, {
        "kdl",
      })
    end,
  },
}
```

I'm new to neovim but I think it works as I now get syntax highlighting, structural selection and am able to `:InspectTree` a kdl file:
<img width="1345" alt="image" src="https://github.com/kdl-org/kdl/assets/300791/5c4dfb2f-0745-4bd2-bbda-9f958440f9d6">

Would you welcome a PR of some sort to indicate this as a potential setup in the readme, for example?

**Comment by zkat** [comment]
@sp3ctum that should really be part of the plugin's readme, not this repo.

**Comment by zkat** [comment]
Nothing else to do here. kdl.vim and tree-sitter-kdl both exist now and are linked from the README.

**Comment by wommy** [comment]
https://github.com/kdl-org/kdl/issues/258#issuecomment-1890912634

```diff
   {
-     "nvim-ts-context-commentstring",
+     "JoosepAlviste/nvim-ts-context-commentstring",
     opts = {},
     config = {
       kdl = "// %s",
     },
   },
 }
```
