### ISSUE TITLE
Test files include tests that disagree with spec

### ISSUE THREAD

**Issue by pingiun** [kdl-org/kdl#266]
I'm not 100% sure how the test cases are expected to work, because some input tests don't have a corresponding file in expected_kdl. I was running my parser against all the files in the input directory and found the `underscore_at_start_of_hex.kdl` file. According to the grammar in the spec, underscores at the start of numbers should not be allowed

**Comment by zkat** [comment]
https://github.com/kdl-org/kdl/blob/main/tests/README.md#full-document-test-cases

input files with no corresponding file in`expected_kdl` are supposed to be parser errors :)

**Comment by pingiun** [comment]
Thanks, I must've missed that sentence
