### ISSUE TITLE
Formal grammar and spec text disagree on whether children terminate node

### ISSUE THREAD

**Issue by bgotink** [kdl-org/kdl#274]
The spec states

> Finally, a node is terminated by either a [Newline](https://github.com/kdl-org/kdl/blob/main/SPEC.md#newline), a [Children Block](https://github.com/kdl-org/kdl/blob/main/SPEC.md#children-block), a semicolon (;) or the end of the file/stream (an EOF).

which implies the following would be valid:

```kdl
node { node {} }
```

The grammar disagrees:

```
node := ... (node-space* node-children ws*)? node-space* node-terminator
node-terminator := single-line-comment | newline | ';' | eof
```

**Comment by zkat** [comment]
oh my. Looks like the prose needs to be updated, then. Happy to take a PR for rewording that if you're willing. The grammar definitely takes precedence when there's an apparent disagreement.
