### ISSUE TITLE
Website and Readme point to two different kdlpy packages

### ISSUE THREAD

**Issue by eugenesvk** [kdl-org/kdl#321]
website
https://github.com/daeken/kdl-py

readme
https://github.com/tabatkins/kdlpy

Not sure which one (or maybe both) should be referenced, but it should be consistent

**Comment by tabatkins** [comment]
I took over the `kdl-py` package name on pipy (with the blessing of daeken) so I suppose it should point to mine.

**Comment by tabatkins** [comment]
Done. https://github.com/kdl-org/kdl-org.github.io/pull/31
