### ISSUE TITLE
Grammar seems to allow multiline after line continuation despite the Spec

### ISSUE THREAD

**Issue by eugenesvk** [kdl-org/kdl#322]
Spec tells us that only single-line comments are optional after whitespace characters

> A line continuation is a \ character followed by zero or more whitespace characters and an optional single-line comment. 

The grammar defines
```escline            	:= '\\' ws* (single-line-comment | newline)```
but then `ws` also includes multi-line comments
```ws                 	:= bom | unicode-space | multi-line-comment```

Which one is supposed to be correct in this case? Or is this properly resolved via some other rule?

**Comment by zkat** [comment]
This is fixed in the kdl-v2 branch now.
