### ISSUE TITLE
Vertical tab U+000B missing from the whitespace table

### ISSUE THREAD

**Issue by eugenesvk** [kdl-org/kdl#331]
When comparing the list of whitespace with some regex engine predefined list of whitespace I've noticed that KDL spec table includes horizontal `U+0009`, but is missing vertical tabspace `U+000b`

Is this just a simple omission or is there a reason one whitespace tab does not belong?

https://www.compart.com/en/unicode/U+0009

https://www.compart.com/en/unicode/U+000b

**Comment by tabatkins** [comment]
(Reverted, since this should have gone into the v2 branch as a technically-breaking change.)

**Comment by zkat** [comment]
I'm actually gonna close this, since it's already in the v2 branch
