### ISSUE TITLE
KDL 2.0: identifier-based quoteless strings

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#339]
I thought a lot about this (and we've talked about this at length in https://github.com/kdl-org/kdl/discussions/308, but I think we should just do it, and that it's going to be ok. In practice, there will be ways to catch typos in a reasonable way, and I think quoteless strings (following identifier syntax) are actually a huge UX improvement for human-authored/maintained configuration files.

Feel free to protest this change here, or up/downvote with reactji, but I'm now leaning towards this being a major KDL 2.0 change.

**Comment by larsgw** [comment]
I think this, especially when combined with #340, can be very confusing. Of course a good linter can prevent such confusion. E.g.

```
ident ident ident          =ident
```

**Comment by zkat** [comment]
After thinking about it I think I'm going to withdraw this. I have an alternative proposal.

**Comment by zkat** [comment]
After conversation in #350, it looks like this is what we're gonna go with after all...

**Comment by zkat** [comment]
This has been merged into the kdl-v2 branch
