### ISSUE TITLE
Why is comma disallowed from idents?

### ISSUE THREAD

**Issue by tabatkins** [kdl-org/kdl#346]
The current set of disallowed chars in idents is `\/(){}<>;[]=,"`, which fall into three categories: grouping chars `(){}<>[]`; chars used for other KDL syntax `\/;="`; and then a comma. Why is the comma, specifically, disallowed here? Was it intended to be a part of KDL syntax at some earlier stage and accidentally stuck around?

**Comment by zkat** [comment]
this is for KQL, so you can have selectors like `foo,bar`
