### ISSUE TITLE
KDL 2.0: whitespace in more places

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#355]
More places should support whitespace:

* Inside `(foo)` annotations (so, `( foo )` would be legal (`( f oo )` would not be, since it has two identifiers))
* Between annotations and the thing they're annotating (`(blah) node (thing) 1 (x) y=2`)
* Around `=` for props (`x = 1`)

**Comment by tabatkins** [comment]
All in all good, tho note that you can't tag a property name (your `(x) y=2` bit; it would be `x=(y) 2`)

**Comment by zkat** [comment]
ah right.

**Comment by zkat** [comment]
This is addressed in the kdl-v2 branch now.
