### ISSUE TITLE
Set up a basic web page

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#36]
Um so.

I bought kdl.dev. Should probably put something up there haha.

**Comment by scotttrinh** [comment]
What's the general vibe? Focus on the spec itself, or more of an example-based "marketing"-focused approach?

**Comment by zkat** [comment]
Mainly a "marketing" / intro site where people unfamiliar can get a quick rundown of what it is, how to use it, and where to learn more

**Comment by scotttrinh** [comment]
Any reason this should be more complicated than a single HTML page with CSS? Could probably go pretty far with just Tailwind or something like that and not need a build process or a CMS.

**Comment by zkat** [comment]
I haven't built a website in a very very long time so I have no idea. But yes something static and simple and maintainable is best. With support for multiple pages probably

**Comment by zkat** [comment]
Looks like 11ty would be really nice for this!

**Comment by scotttrinh** [comment]
I can throw together something that basically copies most of the readme into a basic 11ty repo.

**Comment by zkat** [comment]
That would be amazing! Thank you so much! Should I make a gh.io repo for you?

**Comment by scotttrinh** [comment]
Whenever you get a chance, no rush. I'll go ahead and get it started today! 🎉

**Comment by scotttrinh** [comment]
I have a very very very basic 11ty + Tailwind project set up and ready to push to a fork of whatever repo you have set up. Definitely more work can go into things like git hooks for formatting, and getting the tailwind tree-shaking working, but everything seems to be working.

**Comment by zkat** [comment]
@scotttrinh https://github.com/kdl-org/kdl-org.github.io here you go! You should have push access, too!

**Comment by scotttrinh** [comment]
Awesome, thanks! I should be able to get everything up and building with Github Actions soon. Saw you added a CNAME, so I'll make sure that is working. Should I just commit directly to `main` for now or do you want a chance to review via PRs?

**Comment by zkat** [comment]
That CNAME is so https://kdl.dev goes to the right repository. You can move it anywhere you want--it just has to be wherever the (rendered) website root will be (if this is something other than `docs/` lmk and I'll change the setting on the repo)

**Comment by scotttrinh** [comment]
Made some progress over at the repo. Does it make sense to close this issue and move any discussion related to the website over there?

**Comment by zkat** [comment]
Yep! Sounds good! Great job and thanks again <3
