### ISSUE TITLE
Indicate invalid tests in filename?

### ISSUE THREAD

**Issue by tabatkins** [kdl-org/kdl#365]
Currently, if you're reviewing the test suite and want to know if a given test is meant to pass or fail, you have to go check the `expected/` folder to see if there's an output file there or not. That's slightly annoying. Could we *also* indicate that something is meant to fail in the filename? Like a `_FAIL` at the end or something.

Then we can add a lint that verifies that every test ending in `_FAIL` lacks an expected file, and vice versa, to make sure these two signals don't drift out of date.

**Comment by zkat** [comment]
That would be nice yes. The suffix would absolutely be easiest (maybe keep it lowercase because git can get weird with casing in some OSes)
