### ISSUE TITLE
[v2]: Case sensitivity for keywords?

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#380]
Can/should we make keywords case insensitive? That is, `#true`, `#null`, `#nan`, etc.

**Comment by larsgw** [comment]
I feel like these alternatives are mainly just things that people are going to want to write linter rules against. But I had the same feeling about quote-less strings, and maybe alternatives are fine.

**Comment by tabatkins** [comment]
Similar to the "I'll probably type `#NaN`" thing, depending on whether I've been most recently writing Python or JS my fingers naturally spell it `True` or `true`.

So I guess I'm weakly for making them insensitive (but maybe with a recommendation about using lowercase as the canonical serialization?)

**Comment by zkat** [comment]
Closing this: just keep them lowercase
