### ISSUE TITLE
[v2] Proposal - "rest of line" strings

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#402]
This was proposed by @imsnif a while back, and I don't think we gave it a proper discussion. I think there's a compelling argument to having "rest of line" raw strings.

So here's the idea, and feel free to lmk what you think!

A value that starts with `#!` will treat all following characters as literal string characters until the new `Newline`

That is, the the following two nodes are equivalent:

```kdl
node1 foo=bar #!cargo run -- C:\foo\bar.exe # //foo
node2 foo=bar ##"cargo run -- C:\foo\bar.exe # //foo"##
```

Notice how we don't need multiple `##` because the actual ending is the `Newline`, so having more `#` along the way doesn't matter.

I'm not like, super genki about this looking at them both side-by-side, but I think there's still some value in it for some very real use-cases (like zellij's cmd nodes!).

**Comment by IceDragon200** [comment]
`#!` is typically [shebang or hashbang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29), even if it's a document format, it could get confusing.

```
node1 foo=bar #>cargo run -- C:\foo\bar.exe # //foo
node2 foo=bar ##"cargo run -- C:\foo\bar.exe # //foo"##
```

I propose `#>` instead, `>` points right implying the user should look to the right for the end of the string

```
node {
  compile foo=bar #>mix compile
  release bar=foo #>mix release --overwrite
  run fizz=buzz {
    cmd #>/opt/app/bin/app run
    env {
      CONFIG_PATH #>/etc/app/config.kdl
    }
  }
}
```

**Comment by larsgw** [comment]
IMO this might overcomplicate the format a bit. You could get the following file, which compiles but behaves unexpectedly.

```
node { foo #> bar; }
node #>bar {
  baz qux
}
```

is equivalent to

```
node {
  foo " bar; }"
  node "bar {"
  baz "qux"
}
```

**Comment by zkat** [comment]
Yeah that makes sense. I’m also not sure it would be worth adding a FOURTH string format to the language just for two characters worth of convenience

**Comment by zkat** [comment]
Because of the footgun that Lars mentioned, I'm going to close this one. I think typing two more characters (`"#`) isn't really worth optimizing any further, now that simple cases can be covered by identifier strings.

**Comment by tabatkins** [comment]
Agreed, this matches with my own opinions on the matter.
