### ISSUE TITLE
Add a "used by" section or page

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#408]
### Discussed in https://github.com/kdl-org/kdl/discussions/396

<div type='discussions-op-text'>

<sup>Originally posted by **Tamnac** August 11, 2024</sup>
I recently found kdl through the niri project, and it looks like a very nice language. I'd be curious what other projects use it too at this point.</div>

**Comment by tabatkins** [comment]
Used by Bikeshed, in <https://github.com/speced/bikeshed-boilerplate/blob/main/boilerplate/doctypes.kdl> and <https://github.com/speced/bikeshed-data/blob/main/data/manifest.txt>
