### ISSUE TITLE
Request for clarification re: serialization of numbers for tests

### ISSUE THREAD

**Issue by Alch-Emi** [kdl-org/kdl#411]
Hi!  I've been working on implementing a kdl 2.0 parser/serializer in Elm, but I'm running into issues with a couple of tests.

I chose to represent numbers as a BigRational so that I didn't have to worry about accidentally mangling a number that didn't fit within Elm's i32 or floating point type, but I encountered a bit of a hitch when running the tests.

Because BigRational doesn't make a distinction between `1.0` and `1`, my serializer renders both of these numbers as `1`.  Similarly, both `1e1` and `10`, so both of those numbers get rendered as `10`.

I can definitely attach some additional information to each number to track if it's a "float" or an "integer", but I wanted to make an issue to ask about it first, and maybe even request that additional clarification be added.

If implementations are meant to keep a distinction between floats and non-floats (even if their internal representation varies), it would be nice if that distinction be made in the spec, especially wrt some more ambiguous "floats", like 2.0 and 1e1.  If that's not a distinction implementations are meant to track, perhaps the tests could use some less ambiguous numbers (e.g. using `1.1e-10` instead of `1.0e-10` in the `negative_exponent` test).  Alternatively, maybe more detail could be added to the serialization spec as to when the trailing `.0` should be added, and past what magnitude large integer numbers should be rendered as `1.0e9` instead of `1000000000`?

Any input appreciated, and thank you very much!

**Comment by zkat** [comment]
For small things like this, it’s totally fine to have a patch that modifies the official tests to match the constraints of your particular parser. There is no concrete requirement about number representation, so wherever something is printed as `1` or `1.0` does not matter, as far as KDL is concerned.

The only numeric thing that might be tricky are the keyword numbers (`#inf/#-inf/#nan`), but I think it’s perfectly fine for an implementation to choose that it’s going to default those to a particular number, or even choke. What matters is that these limitations be known and documented for a given impl.

But that’s my 2c. Others might have stronger feelings about cross compatibility than that.

**Comment by Alch-Emi** [comment]
Makes sense!  Thanks for the advice!

**Comment by Alch-Emi** [comment]
After spending a little more time reading issues, I found one I missed in my initial search.  I think this issue is effectively a duplicate of #252.  Adding this note after-the-fact in case anybody in the future finds this issue but not the other.
