### ISSUE TITLE
[v2] v1 vs v2 parsing: multiline string ambiguity + a proposal?

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#413]
I believe that, for any given KDL document, if it parses with both a v1 and a v2 parser, the data will be identical, and thus it's safe to "throw" a kdl doc, of _any_ version, at _any_ parser, and if the parse succeeds, then the data represented will remain intact.

The one exception to this that I've been able to think of is that v2 multiline strings can conflict with v1 strings and:

1. dedent them
2. replace any newlines with `\n` (`LF`)

e.g.:

```kdl
node "
    foo<<CRLF>>
    bar
    "
```

is valid in both versions, but v1 will eval to `"\n    foo\r\n    bar\n    "`, and v2 will eval to just `"foo\nbar"`.

...which is basically data loss.

As a result of this, I'd like to propose that multiline strings use `"""\n` instead of just `"\n`. It might be more verbose, but I think it's a little clearer, it adds no new reserved syntax, and it would make migration from v1 to v2 fully safe because any parser, as long as it succeeds a parse, will give the right data back.

So the above would become the following document, which will parse in v2, and syntax err on v1:

```kdl
node """
    foo<<CRLF>>
    bar
    """
```

Reviewing things/the changelog, I don't believe there's any other "gotchas" for folks who might want to load a `.kdl` file not "knowing" which version it's supposed to be for.

/cc @tabatkins @larsgw

**Comment by tabatkins** [comment]
Honestly yeah, this is nice on is own merits imo. Triple quotes are a common multiline introducer, and multiline strings really are a distinct syntax entity from singlelines.

**Comment by zkat** [comment]
and a PR for it: https://github.com/kdl-org/kdl/pull/414
