### ISSUE TITLE
Copy the v1 spec over to main

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#420]
Since the expectation going forward is going to be, I think, for a lot of parsers to support both v1 and v2 with a fallback, I think it might be helpful to copy over the v1 `SPEC.md` as `LEGACY_SPEC.md`, possibly with some additional information about how backwards compatibility works, and why fallbacks are safe?

**Comment by IceDragon200** [comment]
Kuddle maintains it's v1 implementation alongside v2 so I believe we should keep the v1 spec around for now, no need to call it legacy, just v1.
`SPEC.md` = whatever is the current version
`SPEC_vN.md` = Previous versions (in case v2 ever becomes the "legacy")

Or maybe just provide a link to the original versioned release (https://github.com/kdl-org/kdl/releases/tag/1.0.0).
No need to include the v1 spec in the tree if we already had it previously.
Just a quick blurb to say that v1 is in feature freeze, or is no longer being changed and can be considered _stable_ (bugs and all).
