### ISSUE TITLE
`multiline_string_whitespace_only` test wrong?

### ISSUE THREAD

**Issue by tabatkins** [kdl-org/kdl#429]
Per spec:

> Empty lines can contain any whitespace, or none at all, and will be reflected as empty in the value:

The example following that line just shows off a completely empty line (lacking the required ws prefix), but [`multiline_string_whitespace_only`](https://github.com/kdl-org/kdl/blob/main/tests/test_cases/input/multiline_string_whitespace_only.kdl) tests a string (the last one) that *does* contain the required prefix, and then some extra whitespace after. The [expectation file](https://github.com/kdl-org/kdl/blob/main/tests/test_cases/expected_kdl/multiline_string_whitespace_only.kdl) expects the additional whitespace to be reflected into the string's value.

I think it shouldn't be doing that - the expectation should have the final string just contain a newline and nothing else.

If the current test expectation is correct, then the spec is ambiguous - what happens when a line just contains *some* of the final-line whitespace, but not all? What if it starts with a different whitespace entirely?

(This test was recently added by @tjol; I expect it was just an error.)

**Comment by zkat** [comment]
Yeah that looks to me like it should have just the single newline in it?

**Comment by zkat** [comment]
Also: I think the spec is pretty clear. You can have literally any whitespace in empty lines, and they will always collapse to a single `\n` (unless it’s the penultimate line, in which case it collapses to nothing)

**Comment by tabatkins** [comment]
Agreed that the spec is clear, I just like having another eye on test changes unless it's *incredibly* obvious it's an error. ^_^

And with that, kdlpy's main branch now passes 100% of the v2 tests, woo!

**Comment by tjol** [comment]
I must have missed that detail.

There's a bit of a tension between

> All in-between lines that contain non-newline characters _MUST_ start with _at least_ the exact same whitespace as the final line

and

> Empty lines can contain any whitespace, or none at all, and will be reflected as empty in the value

in the spec. Maybe "non-newline" should be replaced by "non-whitespace"?

So is the idea that lines can have trailing whitespace if and only if they contain non-whitespace characters? I find that mildly surprising. (only mildly)

I think I'll add a few more tests for different permutations of whitespace and non-whitespace.

**Comment by zkat** [comment]
@tjol yeah, maybe just change that to:

> All in-between lines that contain non-newline, non-whitespace characters MUST start with at least the exact same whitespace as the final line

**Comment by tabatkins** [comment]
> So is the idea that lines can have trailing whitespace if and only if they contain non-whitespace characters? I find that mildly surprising. (only mildly)

No, if you want a line with just whitespace in it, you can start the content part (after the indent prefix) with an escape for a ws char, then whatever follows can be normal whitespace. Escapes are considered non-ws content for the purpose of indent stripping.

(You can't do that with raw strings, as part of the general loss of ability to use escapes to insert some disallowed literal characters.)
