### ISSUE TITLE
Ruby parser

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#53]
We should have a nice Ruby parser for kdl. Hopefully we can also add it to the org!

**Comment by jellymann** [comment]
@zkat I've got an implementation I've been working on here: https://github.com/jellymann/kdl-rb

**Comment by zkat** [comment]
Oooh! Awesome! Feel free to make a pr to this repo when you think it's ready and we'll add it to the list of implementations!

**Comment by jellymann** [comment]
@zkat Alright I think it's ready 😅
