### ISSUE TITLE
Go parser

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#54]
We should have a nice golang parser for kdl. Hopefully we can also add it to the org!

**Comment by gcapizzi** [comment]
giving a go (heh) at this using https://github.com/alecthomas/participle, not sure I'll get anywhere, wish me luck! 😅

**Comment by zkat** [comment]
Good luck!

**Comment by gcapizzi** [comment]
Alright, I'm a bit stuck.

`participle` is quite rigid in terms of the ASTs that it can generate. In particular, it maps variants as `struct`s with multiple fields, only one of which has a value. For example, to allow interleaved values and properties as arguments, we would have to add an `Argument` `struct` with `Value` and a `Property` fields. Same for the `Value` type.

It would be a lot nicer to have separate `Values` and `Properties` lists (just like in the Rust parser), but I don't think there's a good way to do this in `participle` 😞 

I _could_ try to handwrite a lexer and a parser, but I've never done it and I'm not sure I'd get to the bottom of it 😅  
Alternatively, we could parse with `participle` and _then_ convert the AST into the one we like. This would mean three passes though (lexing + parsing + "fixing" the AST).

I was also thinking that a tags-based solutions would be pretty nice (that's what the [`json` package](https://golang.org/pkg/encoding/json/) does for example). I don't think that would save us from building a more traditional AST-producing parser though (the `json` package has one, which produces `map[string]interface{}`s).

Thoughts?

**Comment by zkat** [comment]
I have never done Go so I don't really know what the best thing would be.

I will say, though, that I don't think parsing speed is that important as an initial goal, so "fixing" the AST seems ok to me?

**Comment by danderson** [comment]
I just came across KDL, and as it happens it's _exactly_ what I needed for a Go project of mine, for which I was in the middle of writing a parser for a custom language. I'm going to retool that to parse KDL instead.

I can't promise I'll get anywhere, so please don't view this as me planting a flag or anything, just broadcasting in case anyone else is interested in collaborating.

**Comment by binhonglee** [comment]
I got started working on this like yesterday so it only works on really small selection of cases. I've never worked on a parser before either, open to suggestions / PR etc.

https://github.com/binhonglee/kdl-go

**Comment by zhengpd** [comment]
Both <https://github.com/binhonglee/kdlgo> and <https://github.com/danderson/go-kdl> are inactive since 2021. Are they abandoned?

**Comment by danderson** [comment]
In my case, yes, sorry. I lost my use-case for KDL, and the time to build the library. My vague memory is that I had a pretty solid lexer, but no parser yet.

**Comment by Frixuu** [comment]
No unmarshalling/marshalling _yet_, but I have somewhat of a working parser at <https://github.com/Frixuu/KDLGo>. Like above, I'm just putting it out there etc. etc. :wink:
