### ISSUE TITLE
Java parser

### ISSUE THREAD

**Issue by ianmcorvidae** [kdl-org/kdl#56]
I don't personally care much about Java proper, but others do and an implementation would be a basis for Scala, Clojure, etc. as well

**Comment by hkolbeck** [comment]
I have a good start of an ANTLR-based parser here: https://github.com/hkolbeck/kdl4j

It currently has a few issues around raw strings that I'm working to resolve.

**Comment by hkolbeck-streem** [comment]
I ditched ANTLR and wrote it by hand. The result is still alpha-quality, but has ~90% test coverage over the interesting bits. There are a few TODOs as noted in the README, but overall it should be usable.

**Comment by hkolbeck-streem** [comment]
It now passes all tests from the Rust impl as well as a large additional test suite designed to be reusable for other parser impls, with 1-2 exceptions where the reference impl disagrees with the spec (mostly around '_' in numbers). I also added a utility to search, filter, and mutate KDL document objects without making the objects mutable: https://github.com/hkolbeck/kdl4j/blob/trunk/src/main/java/dev/hbeck/kdl/search/Search.java

If it looks solid enough to you, I'd like to add it to the page.

**Comment by zkat** [comment]
@hkolbeck-streem looks good to me! Ship it! 👍🏻

**Comment by borland** [comment]
having ported it to .NET, kdl4j looks pretty awesome right now; Suggest closing this issue in favor of it?

**Comment by zkat** [comment]
yep! :)
