### ISSUE TITLE
Improve Full Grammar in specification

### ISSUE THREAD

**Issue by broeser** [kdl-org/kdl#64]
Hello,

I have very little experience with grammars, parsers etc. but still thought I could maybe try working on some tools for KDL (parsing, linting, syntax highlight plugins, not sure yet…).

1. I read the https://github.com/kdl-org/kdl/blob/main/SPEC.md#full-grammar section from the specification and don't understand it. Is it EBNF? To my limited knowledge, then it's not syntactically correct, for instance the := should be ::= – or is it another format? I suggest adding some notes regarding that to / below the "Full Grammar" headline.
2. There are references to the tables above (for unicode-space and newline), which make it impossible for the grammar to be used by a machine. Is that because the spec is still work-in-progress, or is that because the full grammar is intended for humans?
3. I tried changing the parts I mentioned by replacing := by ::= and by removing the parts mentioning the tables above, then feeding it to https://bottlecaps.de/rr/ui (which looks helpful for generating diagrams e.g. for documentation). I got a syntax error on line 11 (`identifier-char ::= unicode - linespace - ["\{}<>;[],"]`), I can probably go forward and fix it myself, however I'd like some input whether what I am trying here even makes any sense

Thanks!

**Comment by zkat** [comment]
The grammar isn't in any format specification. It's mostly a grammar spec style I've cobbled together over the years that expresses things in a way that makes sense to me (and also others). I've thought about rewriting it in a simpler form, possibly like JSON's, but I just used what I'm most comfortable with.

**Comment by zkat** [comment]
Thinking about it, I'm perfectly happy with the current grammar. It has a few extensions that make it easier to parse, and it's been clear enough to be useful to a number of implementors, so I'm just going to close this out since there hasn't been any further interest in actually providing a PR to improve this.

**Comment by eugenesvk** [comment]
Full formal grammar would be nice to have

For example, there is this tool https://github.com/BenjaminSchaaf/sbnf I haven't tried that allows building Sublime Text syntaxes based on ebnf-style grammar, so if KDL had a formal grammar it might've been easier to convert (also more future-proof as updating a single table of grammar is easier than updating hand-crafted syntaxes)

Understand that there might be no interest yet in actually implementing it, but that's a different question re. whether this is a worthy goal, so maybe this issue could be reopened to signal the latter?
