### ISSUE TITLE
PHP parser

### ISSUE THREAD

**Issue by shieldo** [kdl-org/kdl#65]
Just for an FYI I've been working on a parser in PHP (!) using the [Parsica](https://parsica.verraes.net/) library, which is based on [Megaparsec](https://hackage.haskell.org/package/megaparsec) in Haskell. Working branch is here https://github.com/shieldo/kdl-php and progress is good - been transferring tests over from the Rust parser and going through everything to iron out edge cases. Hoping to have a complete implementation very soon!

**Comment by larsgw** [comment]
I have the start of a test suite (I don't know if it's any good but it caught a bug in my parser) over at https://github.com/kdl-org/kdljs/tree/main/test.

**Comment by shieldo** [comment]
OK I have what I think is a fairly complete implementation! It's slow, for now, but the lib is focussing on correctness over speed.

https://github.com/shieldo/kdl-php/releases/tag/0.1.0

Is there a wish to include this implementation with the org? If not, I can publish under my own namespace - I'd like to add it to Packagist (central PHP package repository) and don't want to have to change the name there right out of the gate.

**Comment by zkat** [comment]
@shieldo wow awesome! Thank you!

As far as whether to include it in the org: that's up to you! If you do give it to the org, I'll give you admin privs so you can manage it yourself, though. Let me know! And feel free to do a PR to add it to the impl list in README and kdl.org once that's done :)

**Comment by shieldo** [comment]
@zkat Yes, I'd like to give it to the org so that it's in a central place - would also be very happy to manage e.g. publishing to Packagist and the like! Lmk and I can migrate it over :)

**Comment by zkat** [comment]
Go for it!

**Comment by zkat** [comment]
@shieldo you should have an org invite now

**Comment by zkat** [comment]
@shieldo do you want to PR adding this to the list of implementations in this repo's README, and on the website? Then we can close this issue out :)

**Comment by zkat** [comment]
actually I'll just do it myself, in retrospect. It'll be quick enough :)
