### ISSUE TITLE
clarification about underscore chars in decimal numbers

### ISSUE THREAD

**Issue by shieldo** [kdl-org/kdl#69]
I'm unclear about whether, and where, KDL allows underscore characters within decimal values.

The text description within the spec does not mention underscores for inclusion within a decimal value. The grammar is shown as:

`decimal := integer ('.' [0-9]+)? exponent?`

This suggests that an underscore is allowed before any decimal point (as it is part of the grammar for an integer value), but not afterward.

However, within the test suite for the Rust implementation there are both the assertions:

```rust
        assert_eq!(float("123_456_789.0_"), Ok(("", 123456789.0f64)));
```

and

```rust
        assert!(float("1._0").is_err());
```

suggesting that an underscore is acceptable in the decimal part so long as it is not the initial position.

Could this be clarified?

**Comment by broeser** [comment]
"integer" is defined in the spec:
`integer := sign? [0-9] [0-9_]*`

So there may be a _ after the first digit.

**Comment by zkat** [comment]
Hm. This looks like an oversight to me. I'll look into clarifying it, yeah.
