### ISSUE TITLE
Relicense to allow usage in non CC-BY-SA 4.0 compatible projects

### ISSUE THREAD

**Issue by jkoritzinsky** [kdl-org/kdl#76]
Based on a [conversation on Twitter](https://twitter.com/zkat__/status/1349606107635826689?s=21), we realized that the current license may be overly restrictive and may prevent projects that are already licensed under MIT from adopting usage of KDL.

This issue came to a head because the new kdl-net parser and its basis, kdl4j, are both licensed with CC-BY-SA 4.0 like the spec and I realized that I might not be able to use it in my projects like SharpGenTools that have been around too long, have too many contributors to contact, or have customers that wouldn't be able to use SharpGenTools if it was licensed with a SA-compatible license.

**Comment by hkolbeck** [comment]
I am not attached to the current license of kdl4j, and will happily re-license to a non-SA one.

**Comment by larsgw** [comment]
Does the license of the specification matter here? Based on [this Stack Exchange answer](https://opensource.stackexchange.com/a/7328/21655) I would think re-licensing kdl4j would suffice, but the answer is not sourced so I may be missing something.

**Comment by zkat** [comment]
@jkoritzinsky As the main author of the spec, I can assert that my intention was for the _specification text_ to be covered under CC-BY-SA 4.0, and I do not consider implementations to be "derivative works", but their own works, just like the Stack Exchange link above.

Fortunately, there are no patent or trademark issues at stake here, so I'm also not very concerned about that second link.

Does that satisfy your concern? As Lars says, I believe relicensing kdl4j would be sufficient to allow you to make a derivative for C# from that code.

If that's the case, I'll make a PR to add an answer to the FAQ to clarify this and make it official.

**Comment by jkoritzinsky** [comment]
Yes, that satisfies my concern. If kdl4j and kdl-net relicense, then I'll be all set.

**Comment by hkolbeck-streem** [comment]
I've relicensed kdl4j to CC 4.0 Attribution: https://github.com/hkolbeck/kdl4j/blob/trunk/LICENSE.md

**Comment by zkat** [comment]
And I've clarified the licensing issue in the README: https://github.com/kdl-org/kdl#license

**Comment by borland** [comment]
I've updated kdl-net to also use CC 4.0 Attribution following kdl4j

https://github.com/borland/kdl-net/blob/main/LICENSE.md
