### ISSUE TITLE
Clarification about unicode FULLWIDTH EQUALS SIGN (\u{FF1D})

### ISSUE THREAD

**Issue by hkolbeck** [kdl-org/kdl#77]
In the readme, the unicode example `ノード　お名前＝"☜(ﾟヮﾟ☜)"` uses a fullwidth equals sign rather than the ascii equals sign. That does not appear to be supported in the spec and the [rust impl doesn't appear to support it either](https://github.com/kdl-org/kdl-rs/blob/main/src/parser.rs#L154). Should the spec be fixed, or the readme?

**Comment by zkat** [comment]
@hkolbeck that's my mistake! I'll fix it in the README.
