### ISSUE TITLE
Support schema definitions

### ISSUE THREAD

**Issue by natemoo-re** [kdl-org/kdl#83]
I'm not positive what the structure of schema definitions would be, but authoring KDL files would be easier with an official way to provide document schemas. Schemas could be permissive (and not necessarily enforced by parsers) or more strict (so authors could validate user documents), but I am mainly thinking they could be used to provide IDE completions and warnings similar to JSON's [`$schema`](https://json-schema.org/understanding-json-schema/reference/schema.html) keyword.

Very happy to contribute to this effort if there is interest!

**Comment by zkat** [comment]
Having a schema language for KDL would be awesome! I fully support this effort, although I would want it to be a separate spec from KDL itself?

**Comment by zkat** [comment]
I've started a schema sketch over at #104. Comments welcome!
