### ISSUE TITLE
New data type proposal: symbols

### ISSUE THREAD

**Issue by daeken** [kdl-org/kdl#89]
I propose the addition of a new data type for KDL that I've been calling Symbols. These are a way to use an identifier (either bare or quoted) as a value for arguments or properties.

# Motivation

It's often valuable to differentiate between a value that's a string literal, versus a value that's talking about an identifier. It is not always *necessary* for that differentiation to occur, but it can be helpful for clarity in cases where it's not strictly necessary.

## Example 1: binary data format specification

```
struct :Zon {
	fixed-string "EQGZ"
	uint32 :Version :strlen :numFiles :numPlaceables :numUnk3 :numLights
}
```

This is a simplified example from a specification I'm working on (using kdl-py, which supports the proposed Symbol syntax). The first child node uses a literal string, as this is being matched in the file -- that is, the first four bytes (a "fixed-string", or fixed-length string, in this context) are "EQGZ". The arguments to the second child node are all identifiers that will be parsed as uint32s.  Additionally, the struct itself is being named `Zon`. Differentiating strings from Symbols is necessary here to indicate what is a known value versus what is a placeholder identifier (essentially, a variable).

## Example 2: KDL document conformity specification

```
Pet abstract=true {
    name :string
    is-good :boolean
    pettable :boolean
}

Cat base=:Pet {
    pettable true
}

Dog base=:Pet {
    is-good true
}
```

This might match a document like:

```
Cat {
    name "Vader"
    is-good true
}
Dog {
    name "Yuki"
    pettable false
}
````

While obviously contrived, the use of symbols to refer to specific identifiers (for the base types pointing to the node named `Pet`) and data types shows how symbols can simplify KDL documents. The ability to differentiate between Symbols and strings allows -- like in the binary format spec -- differentiation between a specific thing (a Symbol containing specific identifier) and a value that might refer to it (a string that has the same value as the identifier).

# Proposed syntax

```
symbol := ':' identifier
value := string | number | symbol | boolean | 'null'
```

The `:` character has precedent from the Ruby world (among others), does not conflict with initial characters for any other value type, and does not have any oddities when working in a text editor that does not natively support KDL, as `'` might (with the editor believing it to be the beginning of a string).

## Other options considered:

- `'` (dismissed due to the aforementioned editor issue)
- `&` or '*' (dismissed due to its use possibly leading to confusion that a reference association exists, when that may not be the use)
- `#` (dismissed due to its use in raw strings)
- `$`
- '@'
- '!'

I believe the last three would be suitable options, but they personally didn't feel right to me while working on this. That's by no means a rigorous argument against them, so I'd have no problem backing those if others feel like they're a good option.

I also considered the option of a different type of quoted identifier (e.g. backticks or parentheses) but these add another level of complexity to parsing KDL; the use of an unambiguous starting character is a much lower lift.

# Implementation

As noted above, kdl-py currently implements this draft proposal, if you'd like to play around with it. If accepted, I'd be happy to put in PRs for the spec, documentation, and at least some of the implementations already out there. The implementation burden for this change is quite minimal, considering how much simpler it can make some documents.

**Comment by zkat** [comment]
I was thinking about this and I still don't know how I feel about adding another whole data type.

At the same time, how would you feel if :symbols were instead a third string syntax, where they would be treated just like strings, but you can prefix them with `:` if they're valid identifiers to make them look nicer? Would that work for your use-case?

Of course, a document-oriented parser in this case _could_ treat Symbols as their own data type, but the _intent_ would be that they be strings, and that would be considered correct. There's no requirement that parsers be able to round-trip cleanly, after all.

**Comment by hkolbeck** [comment]
It definitely feels like for symbols to be useful they'd have to be round tripped, which either means a separate datatype (which seems to me like a fair amount of work for a use case that's a nice-to-have) or making a standard for round-tripping strings. I've definitely thought a lot about the latter in the context of [kq](https://github.com/hkolbeck/kq), but I don't think it should be part of the language spec.

I know I'm not a core contributor, but I'd argue against including symbols.

**Comment by larsgw** [comment]
I have not succeeded in organizing these thoughts but:

  - Overall, whatever code ingests the parsed KDL has ultimate control over how data is interpreted, and could also have control over how data is outputted. I like the idea of Symbols and I see how they *could* be a separate data type, but not really why (as they are nearly strings). That said, you could say the same about numbers. I suppose the difference is that numbers follow a set pattern, but Symbols could really just be any string?
  - The `identifier` rule in the grammar includes strings. This is not necessarily a problem, I think, but it could look weird.
  - `:` is a valid initial character for identifiers, if I am not mistaken. In the current grammar that is fine, but it makes it harder to find out whether you are parsing a Symbol or a key in a key-value pair, and it makes something like #41 hard as well.

Overall, I have not really found a hard argument against Symbols proper. I do think that however nice it looks, this would not be a great syntax for strings if they do not have any different meaning.

**Comment by zkat** [comment]
I think interest (my own included) in this is pretty low, and @daeken's original use case is no longer relevant, so I've decided to just close this as part of cleanup as we head to 1.0.
