### ISSUE TITLE
Clarification about `[` and `]` in identifiers

### ISSUE THREAD

**Issue by jam1garner** [kdl-org/kdl#90]
The last mention of `[` or `]` in identifiers I can find mention of is #35, "prevent [ and < and { from being used as initial node characters" which... makes it sound like they're legal in non-initial positions. However upon trying to use the reference implementation, this fails to parse.

When checking the spec, the reference implementation [seems to be correct](https://github.com/kdl-org/kdl/blob/main/SPEC.md#non-identifier-characters). However this addition to the spec predates dissallowing it by uh. [a day (according to git blame)](https://github.com/kdl-org/kdl/commit/0092ad84dbe1906be27bec3f746a510741ee96a9).

The Rust implementation doesn't seem to allow this, but kdl-py does, and it seems like [FluffyPy is dependent on it](https://github.com/daeken/FluffyPy/blob/main/examples/quake3.kdl).

Personally, I find kdl-py's behavior beneficial for my use-case, which is effectively encoding a struct-access syntax as nodes (an example being: `my_struct.some_array[0].some_field`). Is this a stale part of the spec, or is kdl-py's behavior incorrect?

**Comment by hkolbeck** [comment]
[KDL4j](https://github.com/hkolbeck/kdl4j) follows the Rust reference impl and does not allow square brackets in identifiers. https://github.com/hkolbeck/kdl4j/blob/trunk/src/main/java/dev/hbeck/kdl/parse/CharClasses.java#L58
